Alexofp/BDCC

- Scenes/EncountersMenuScene.gd
- UI/NpcList/NPCRow.gd
- UI/NpcList/NPCRow.tscn
- UI/NpcList/NpcList.gd
- UI/NpcList/NpcList.tscn
Added sorting + minor refactoring of the previous code.
> Npclist sorting

- Scenes/ChangeHaircutScene.gd
> ChangeHaircutScene.gd Spelling correction

- UI/MainMenu/CreditsScreen.tscn
Searched internet to know about Mekyro and RRDC……I guess it's "creating"……right?
> spell correction?

- Attacks/NpcAttacks/CuffPCHands.gd
- Attacks/NpcAttacks/DoubleCuffPC.gd
- Attacks/NpcAttacks/ForceBlindfoldPC.gd
- Attacks/NpcAttacks/ForceGagPC.gd
- Attacks/NpcAttacks/ForceMuzzlePC.gd
- Attacks/NpcAttacks/ForceRingGagPC.gd
- Game/SexEngine/SexActivity/DomBondage.gd
- Game/SexEngine/SexActivity/DomPutBreastPumpOnSub.gd
- Inventory/Inventory.gd
- Inventory/ItemBase.gd
- Scenes/FightScene.gd
Give items the ability to trigger effects when force-equipped. Pass through the attacker to check for perks and such.
> items can react to forceful equip

- Util/GameParser.gd
- caused when non penis person use strap on in scene
> Fixed null pointer

- Modules/HypnokinkModule/Characters/HK_Rush.gd
- Modules/HypnokinkModule/Events/HK_HypnoEncounterStartEvent.gd
- Modules/HypnokinkModule/Scenes/HK_DatapadHackComputer.gd
- Modules/HypnokinkModule/Scenes/HK_RushRepeatConversation.gd
- Modules/HypnokinkModule/StatusEffects/HK_Suggestible.gd
- Modules/HypnokinkModule/Util/HypnokinkUtil.gd
All that work on the mod, and of all the things this one minigame I threw together in an hour continues to be what causes trouble. Here's one last modification to make it not require typing anything and make the hints yet more blatant.
...rats, I was hoping Id manage to sneak this in before the bugfix release.
> One-handed play support for the cage unlock minigame

- Scenes/Cellblock/LaundryUniformMachineScene.gd
I leave it to your discretion to decide on the remaining 13 "dying"
> Dying  -->Dyeing

- Game/World/Floors/MainHall.tscn
No roomNme so in game it shows "MainHallRoom48".I wonder if you would like use another roomName……
> get a roomName

- Game/World/Floors/Cellblock.tscn
- Inventory/Inventory.gd
- Modules/CellblockModule/MainCheckpointScene.gd
- Modules/FightClubModule/Entrance/BulldogSexScene.gd
- Modules/FightClubModule/Fighters/Kait/KaitWonScene.gd
- Modules/FightClubModule/Fighters/Nova/NovaLostToScene.gd
- Modules/GymModule/RishaGymScene.gd
- Modules/HypnokinkModule/Scenes/Encounters/HK_HypnoEncounterKneel.gd
- Modules/HypnokinkModule/Scenes/HK_RushRepeatConversation.gd
- Modules/HypnokinkModule/Scenes/HK_VionRepeatConversation.gd
- Modules/MedicalModule/Nursery/NurseryTalkScene.gd
- Modules/RahiModule/RahiTalkScene.gd
- Modules/SocketModule/HelpScenes/SocketHelp4Scene.gd
- Modules/SocketModule/HelpScenes/SocketHelp5Scene.gd
- Modules/SocketModule/SocketTalkScene.gd
- Modules/TaviModule/Chapter2/Ch2a2CorridorScene.gd
- Modules/TaviModule/Chapter2/Ch2t3TaviDrugsScene.gd
- Modules/TaviModule/Chapter3/TaviEngineeringSafeComputer.gd
- Modules/TaviModule/TaviTalkEvent.gd
- Modules/TaviModule/TaviTalkScene.gd
- Player/Player.gd
- Scenes/Cellblock/EatInCanteenScene.gd
- Scenes/Intro/IntroScene.gd
- Scenes/MeScene.gd
- Scenes/Mineshaft/FirstTimeInMinesScene.gd
- Scenes/Mineshaft/WorkInMinesScene.gd
- Scenes/RestingInCellScene.gd
- StatusEffect/Pregnant.gd
I'm a programmer, but for now all I can contribute to this project are nitpicks like these that I noticed while playing.
> Spelling, grammar and punctuation

- UI/SkillsUI/SkillStatLine.gd
- UI/SkillsUI/SkillStatLine.tscn
- UI/SkillsUI/SkillsUI.gd
This PR changes the "+" button to "+1" and adds "+5" and "+10" buttons to increase more stats with a single click, more intuitive than my spinbox PR.(yes, it took me this long to change it)
> New stat up buttons

- Util/Util.gd
This is an issue because if the species does not exist anymore (eg. removing species mod and looking at nursey database)
> Fixed crashing due to null pointer in getting species name

- Player/Player3D/Parts/PartOrient.gd
- Player/Player3D/Parts/PartOrient.tscn
- Player/Player3D/Parts/PartOrientPicker.gd
- Player/Player3D/Parts/PartOrientPicker.tscn
- project.godot
I'm pretty sure I got all the edge cases and I sure hope there is no weird doll scale in the future.
if you have anything you want to changed you can edit them or discuss it with me
> part orientation

- Game/InteractionSystem/Interactions/InSlutwall.gd
- Game/InteractionSystem/Interactions/InStocks.gd
- Game/LustCombat/LustActions/PantiesShakeOff.gd
- Game/LustCombat/LustActions/StartGropeButt.gd
- Game/LustCombat/LustActions/UniformShakeShortsOff.gd
- Game/NpcSlavery/SlaveActionScenes/PunishSlaverySlutwallTalkScene.gd
- Game/NpcSlavery/SlaveActionScenes/PunishSlaveryStocksTalkScene.gd
- Modules/GymModule/BullyGangScene.gd
- Modules/JackiModule/Ch2/jackiCh2s2GymScene.gd
- Modules/TaviModule/Chapter1/Ch1s2Risha.gd
- Modules/TaviModule/Chapter1/Ch1s3Datapad.gd
> Fix: few typos

- Modules/TaviModule/Chapter4/Ch4s5DirectorScene.gd
I dislike making such small pull requests but it is what it is
> Fix grammar in Tavi module (borned -> born)

- Inventory/ItemBase.gd
- Inventory/SmartLocks/Locks/SlutLock.gd
- Scenes/FightScene.gd
> Add inventory description of smart-locked restraints

- Scenes/ParadedOnALeashScene.gd
Hello there!
I've been making a mod for a month or so, and decided to submit this little PR for adding optional pose for player in ParadedOnALeashScene. I think game/mod devs would benefit from additional argument there as it allows for a bit more petplay options of player walking around on their knees instead (personally using "crawl" action in few places for this scene).
> Add positional argument to ParadedOnALeashScene to specify player's pose

- Game/SexEngine/SexActivity/SexVaginalOnAllFours.gd
SexVaginalOnAllFours "strugle" typo
> typo fixed successfully

- Game/InteractionSystem/InteractionSystem.gd
- Game/SexEngine/SexActivity/DomOralSexOnSub.gd
- Game/SexEngine/SexActivity/SexVaginalOnAllFours.gd
- Game/SlaveAuction/Actions/EmphasizeBody.gd
- Game/SlaveAuction/Actions/EmphasizeBreasts.gd
- Game/SlaveAuction/Actions/EmphasizePenis.gd
> Typo fixes

- Game/NpcSlavery/SlaveActionScenes/SlaveryPetWalkiesShower.gd
- Game/NpcSlavery/SlaveActionScenes/SlaveryPetWalkiesTrain.gd
- Game/SexEngine/SexActivity/DomOralSexOnSub.gd
- Game/SexEngine/SexActivity/DomRidingSubVaginal.gd
- Game/SexEngine/SexActivity/DomRimSub.gd
- Game/SexEngine/SexActivity/SexVaginalOnAllFours.gd
- Game/SexEngine/SexActivity/SixtyNine.gd
- Game/SexEngine/SexActivityBase.gd
- Inventory/Items/BDSM/RopeHarness.gd
- Modules/ArticaModule/c1Corruption/Event/articaEventPortalPanties2Scene.gd
- Modules/TaviModule/Chapter6/MasochismMinigame/MasochismMinigame.gd
just smol fixes, also I was told dev branch exists oop
> Typo fixes: "presss" (presses) and "sensetive" (sensitive)

- Skills/Perk/CombatBetterBlock.gd
- Skills/Perk/FertilityProudMom.gd
> Fix 2 typos in perk descriptions

- UI/LaunchScreen/LaunchScreen.gd
- UI/MainMenu/InGameMenu.gd
^ 
* Up/Down = Select next/previous mod
* Left/Right = Move mod up/down
* Space = Toggle mod state
Kinda new to Godot so input is bad but :woman_shrugging:
> Keyboard controls for mod menu and proper "enabled"/"disabled" text on button

- Scenes/RestingInCellScene.gd
Honestly, can't believe this typo survived for so long in such often reoccurring scene lol
> Fix typo in sleeping scene

- Game/SexEngine/SexActivity/SexVaginalOnAllFours.gd
> fix: pose descriptor mixup and press/presses

- Game/InteractionSystem/Interactions/PunishInteraction.gd
- Modules/NpcSlaveryModule/Enslaving/EnslaveDynamicNpcEvent.gd
another 0.1.7 thing that i haven't paid close attention to, but you can clip a leash to someone's collar, restrain them, choke them out etc. all with arms tied and/or paws blocked, which is veeery flexible but seems unintentional \~w\~
> Prevent most PunishInteraction actions with restraints on arms or paws

- Game/SexEngine/SexActivity/DomRidingSubVaginal.gd
- Game/SexEngine/SexActivity/SexVaginalOnAllFours.gd
- Game/World/Floors/MainHall.tscn
i'm not 100% sure on the wording here, but ideally it should probably be "temporarily retrieves the thing out" / "temporarily removes the thing from", just to avoid saying "out" twice
> "temporary takes out a thing out of" -> "temporarily retrieves a thing out of"

- Modules/HypnokinkModule/Util/HypnokinkUtil.gd
i like the idea of needing to look for the right option when trying to resist, but in my opinion obeying shouldn't require the effort to make sure you don't resist by accident \~w\~
hard to explain why i tied it to fetish interest, feels more personalized for those in a specific mindset
changelog:
added "head empty" gameplay
> hypnokink: First action always obeys if pc ReallyLikes/Loves being a subject

- Scenes/Item/PenisPumpMilkingScene.gd
> Fix not being able to milk self if the pump is already worn

- Characters/Dynamic/CharacterPool.gd
- Characters/Dynamic/CharacterType.gd
- Game/Options/ContentType.gd
- Game/Pregnancy/NpcGender.gd
- Game/SexEngine/PersonalityStat.gd
- Inventory/InventorySlot.gd
- Player/Bodyparts/BodypartSlot.gd
- Scenes/EncountersMenuScene.gd
> Refactor: Decoupling for some class

- Modules/RahiModule/2Slavery/Activities/rahiActivityAnalScene.gd
> fix few typos

- Game/Datapacks/UI/DatapackBrowser.gd
- Modules/ElizaModule/Science/ChemistryLabScene.gd
- Modules/RahiModule/2Slavery/Activities/rahiActivityPetplayWalkiesScene.gd
- Modules/SlaveAuctionModule/Mirri/MirriTalkScene.gd
- UI/LaunchScreen/LaunchScreen.gd
- UI/ModBrowser/ModBrowser.gd
> fix some typos

- Scenes/ToiletScene.gd
> Fix able to pee while portal panties is on

- Game/InteractionSystem/CharacterPawn.gd
- Game/InteractionSystem/InteractionSystem.gd
- Game/InteractionSystem/PawnInteractionBase.gd
- Skills/Perk/CumSloppySeconds.gd
This allow to load my main save on Vanilla BDCC without crashes.
This first PR only focus on fixing crashes.
While my main save loads, it load in a semi broken state due to missing bodyparts.
I'll put the bodypart fixing/recovery into it's own separate PR once this PR is reviewed and merged.
> Fix some game crashes when removing mods.
