Modules/Module.gd

Added the following as classes modules can register:
- stageScenes
- lootTables
- lootLists
- fetishes
- sexGoals
- sexActivities
- sexTypes
- fluids
Guessing those should be fine.
Left out stats, skins, imagePacks, lustTopics (not sure if the game can handle extras with those), mapFloors (register function for those has two params) and fightClubFighters (not sure those are actually a separate thing from characters).

Add more stuff into module resolution

---

Characters/Character.gd
Game/BaseCharacter.gd
Game/SexEngine/SexEngine.gd
Inventory/Inventory.gd
Inventory/ItemBase.gd

This adds a function called `isPersistent` to `itemBase`, which is checked for in `sexEngine` and `inventory` to avoid returning persistent items to the player at the end of sex scenes and to avoid clearing them at the start of sex scenes.
It also adds `onSexStarted` and `onSexEnded` to `itemBase` and calls them at the same time as the similarly named functions for effects and the like in `baseCharacter`.
These changes should make it easier for item logic to be run at the start and end of sex scenes, and for items to be given to NPCs permanently, which is useful for the Portal Expansion Mod that I'm making.
Hopefully, there are no edge cases where this code causes something to break.

Persistent items

---

Scenes/FightScene.gd

If player has many bondage items of the same type, is listing through many buttons in combat quite annoying, this update offers only one button for each level and information on available quantity.

Remove duplicate bondage items in fight

---

UI/DebugUI/ConsoleSingleton.gd

fixes crashing when argument size is not equal to what command expects

---

Game/Pregnancy/MenstrualCycle.gd

This PR fixes console or cout print spam from RNG randi_range() that's bugging me on my playthrough.
Here is my issue, in my playthrough I noticed this strange spamming inside the console every time I walk around:
`randi_range() from is higher than to. From = 36 To = 34`
(36 is from calculation of then line 310 and 34 being trueValue)
I have tracked down the problem for me, I haven't test on other saves but it should work fine.
Here's the [save](https://files.catbox.moe/b3zd5w.save)
and you at least require [Hypertus](https://github.com/CanInBad/Hypertus) to load into the save then try walking around

Fixes console/cout spam when deciding max value in getRoughLitterEstimateString

---

Game/SexEngine/SexActivityBase.gd

Seems like simple copy-paste error. Text refers to wrong person in the dialogue resulting in nasty ERROR:NO_VAGINA error on sex.

Fixing targeted object in doSpitCumIntoHoleDom function

---

Game/Datapacks/UI/CrotchCode/VisualSlots/BlockCatcherPanelSmall.gd
Game/Datapacks/UI/CrotchCode/VisualSlots/BlockCatcherPanelSmall.tscn
Game/Options/GlobalOptions.gd

I just recently discovered this thing existed and had no idea you could drag code blocks above others, it wasn't intuitive at all and mobile users had it rough, so i changed the default size of the node and made the size a setting, also added a very thin outline to highlight it

Added new option for adjusting block catcher panel size

---

Game/GM.gd

A feature I have wanted for a hot bit, but basically just, 
if the user has created a `BDCC.data` folder along side the exe, it force sets the `%APPDATA%` environment variable to that folder instead of where it usually is, which results in all save data being stored there, rather than in the account files. 
If I knew how to make a global variable that everything could reference, I would adjust all uses of `user://` to use one, but this is my first time touching godot beyond poking it with a 5ft stick

Add support for a portable data directory.

---

Game/InteractionSystem/InteractionSystem.gd

Sometimes pawns will perform a "justleave" action with 1% probability, even if the threshold/cutout was intended to be set to 10%.

Fix unlikely actions within interactions not being filtered out

---

Game/SexEngine/SexActivity/DomOralSexOnSub.gd
Game/SexEngine/SexActivity/DomRidingSubVaginal.gd
Game/SexEngine/SexActivity/SexOral.gd
Game/SexEngine/SexActivity/SexVaginalOnAllFours.gd
Game/SexEngine/SexActivityBase.gd

Each method call should now have a `showMessages` argument explicitly set to `true`, to shift the position of stretchMult float to the fourth position, in order to match the function definition:
https://github.com/Alexofp/BDCC/blob/110d9ce8e2d8d70d54b3fed19f543dd93d8108ee/Game/BaseCharacter.gd#L1073

Fix orifices becoming loose seemingly quicker than intended

---

Game/Pregnancy/MenstrualCycle.gd

Game generally handles missing elements after save gets opened without mods fine, however when testing some modding stuff I found that this part of code can throw null if species is not found in registry and crash badly. 
This PR uses static default ovulation from BaseSpecies.gd when species doesn't exist preventing the crash.
If this is not the best way to do that I can change it, however that's the only thing I came up with.

Fix bad handling of ovulation after species get removed (like when modding)

---

Scenes/ChangeSkinScene.gd

when I used the character creator for the first time, it took quite a bit of time to try out every possible pattern, and there was no indication of which one was selected, so I propose a smol quality-of-life tweak that doesn't change a lot
\-
without PR:
https://github.com/user-attachments/assets/37152fe8-aab0-4d4b-9975-a4c258cf9422
with PR:
https://github.com/user-attachments/assets/5ad5af3c-22ad-48ec-b6f3-f7cc897a7bd9
\-
I couldn't find a sensible way to prevent skips to page 1, that can be done outside of the PR if desired \~w\~

Allow quicker switching between skin patterns, indicate the selected option

---

Game/BaseCharacter.gd
Game/InteractionSystem/Interactions/HelpingWithRestraints.gd
Game/InteractionSystem/Interactions/InSlutwall.gd
Game/InteractionSystem/Interactions/InStocks.gd
Game/ModularDialogue/Fillers/DefaultFiller.gd
Game/ModularDialogue/Fillers/Dommy.gd
Game/ModularDialogue/Fillers/Mean.gd
Game/ModularDialogue/Fillers/ShySubby.gd
Game/ModularDialogue/FormBanks/Default.gd

Pawns always assume their help with restraints is wanted. With the changes in this PR, offering to help someone with restraints prompts them on whether they wish to be helped, with the name of the restraint being displayed in the event log.
Stocks/Slutwall already has an ability to prevent help, but not before the initial attempt was already made. It's now possible to stop them in anticipation, featuring some dialogue lines added for extra flavor.
NPC's may refuse being helped if they are into bondage and the helping character doesn't have dommyness advantage over them. They will not refuse help if they shouted for help at least once.
\-
Fixes other restraints being removed when someone is being helped to struggle out of stocks or the slutwall, by giving priority to the latter.

Add ability to refuse help with restraints, stocks and the slutwall

---

Game/SexEngine/SexActivity/DomDrugUse.gd

when applying lube, dom would say one of those things
https://github.com/Alexofp/BDCC/blob/f1c6a2bb8fabf22601a467249a74bca977022b7a/Game/SexEngine/SexVoice.gd#L723-L730
could write some generic phrases like "Let's get you ready.." that would still make sense with potential modded items but i'm not creative enough right now x3
so this change just omits the dialogue for now

Skip dialogue when applying lube (or a modded drug/lube)

---

Game/InteractionSystem/Interactions/AloneInteraction.gd

i'll miss walking up to someone just to learn they're "in a AloneInteraction interaction" but it's probably worth a fix x3

Fix "namehere is in a AloneInteraction interaction"

---

Game/InteractionSystem/Interactions/InSlutwall.gd
Game/InteractionSystem/Interactions/InStocks.gd
Game/InteractionSystem/Interactions/PunishInteraction.gd

too easy to farm affection locking someone up then freeing them with restraint key ^^;
approximate numbers with this fix:
\- locked someone up: 29% -> 7%
\- freed them afterwards: 7% -> 22% (before fix you'd get approx. 80%)
this should also work for npcs saving another npc they locked up

Gain much less affection when freeing someone you locked up in stocks/slutwall

---

Game/SexEngine/SexActivity/DomDrugUse.gd

this was part of #174 PR but this implementation is less hacky
"OBEY" will now accept/swallow pill (with ~99.9% chance if other actions are present). i didn't want to mess with "priority" and SexEngine doesn't filter unlikely actions the way InteractionSystem does, hence a silly number of 10000.0 score. feel free to adjust
without this change "OBEY"ing pc would pick unrelated actions like rubbing, ignoring the pill
"OBEY"ing pc would also refuse or spit pill out if they hate drugs:
\- when forcedObedience isn't high enough for pc to have all fetishes as Loves but "OBEY" appeared as result of RNG
\- or when being \*forced\* a drug, where spitting pill out has base score of 0.1
https://github.com/Alexofp/BDCC/blob/924c60c250b22c9cdba7884af8f3ad7f032a67a6/Game/SexEngine/SexActivity/DomDrugUse …

"OBEY" accepts/swallows pill

---

UI/AutoTranslatorMenu/AutoTranslatorMenu.gd
Util/AutoTranslation/AutoTranslation.gd

Previous:
if the autoTranslation function is disabled at first, the translator order list will show nothing even though you enable it.
After:
Translator order list will show contents properly.

fix: When autoTranslation function is enable, the translator order should show items immediately

---

Modules/JackiModule/Module.gd

All functions use variable name as `*Corruption`, which does not affect the functioning but looks strange.

Fix confusing variable name in JackiModule/Module.gd

---

Inventory/LootLists/RestraintKeyList.gd

should the loot table look closer to this, or is it intended that you can get up to 8 restraint keys if you simultaneously succeed the 75%, 50% and 10% RNG checks?
this is most noticeable when looting junkieStash and your character barely carries any keys, so sometimes you get A LOT of keys and i wonder if that's by design

restraintkey loot list

---

Game/InteractionSystem/CharacterPawn.gd
Game/InteractionSystem/Interactions/Talking.gd
Game/InteractionSystem/PawnInteractionBase.gd
Game/LustCombat/LustInterests.gd

flirt by presenting body/bodypart practically never worked for me (which i think happens from negative values, abs of `Interest.Hates` would add 2 to divisor, abs of `Interest.Dislikes` would add 1 to divisor, even if player didnt have that trait they'd end up at 0 out of 2, at best)
i also wanted it to actually tell why it didn't succeed, at least sometimes. it reveals preferences in the process, but i think's fair since failed flirts make lust/affection go down by quite a bit
overall it looks like this

Fix present-flirt failing too often, add text lines which may reveal interests

---

Game/SaveManager.gd

After the recent update, Sometimes when you load a save, the game will crash or just show the start scene. like below (in Chinese sry)
This will happen because when you load a save, the game needs to change to the MainScene, while godot will only load the Node at the next idle frame, so `yield(get_tree(),"idle_frame")` is nessacery. But in the next idle frame, the node loading processes goes with the function `loadGame`. If you are not lucky enough, the `loadGame` will hit `GM.main` first, before the `MainScene` node is fully loaded.
So I used `call_deferred` to trigger the `loadGame` at the end of the frame, which may fix the problem.
For other solution, like using Signal, you can try it if you like.

Fix a temporary severe error when loading a save
